# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12
language: swift
# cache: cocoapods
# podfile: Example/Podfile
before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
  - gem install xcpretty
script:

# Display some environment info.
- xcodebuild -version
- xcodebuild -showsdks
- xcrun xctrace list devices

# Build-a-bear

#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MapCache.xcworkspace -scheme MapCache-Example -sdk iphonesimulator14.0 -destination 'platform=iOS Simulator,name=iPhone 11' ONLY_ACTIVE_ARCH=NO | grep -E "Test Case |\[MAPCACHE\]|error:"

- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MapCache.xcworkspace -scheme MapCache-Example -sdk iphonesimulator14.0 -destination 'platform=iOS Simulator,name=iPhone 11' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
